export enum HttpOperationErrorCodes {
    INVALID_TOKEN_AUTH = 'AUTH_001',
    WRONG_PASSWORD = 'AUTH_002',
    INVALID_ROLE = 'AUTH_003',
    INVALID_AUTHENTICATED_USER = 'AUTH_004',
    USER_WITHOUT_PERMISSIONS = 'AUTH_005',
    TOKEN_NOT_FOUND = 'AUTH_006',
    USER_WITHOUT_ROLE = 'AUTH_007',
    USER_WITHOUT_PERMISSION = 'AUTH_008',
    USER_NOT_FOUND = 'USR_001',
}