export enum PermissionEnum {
  ALL_INCIDENTS_PAGE = 'all_incidents_page',
  INCIDENTS_PAGE = 'incidents_page',
  CREATE_INCIDENT_PAGE = 'create_incident_page',
  INCIDENT_TYPES_PAGE = 'incident_types_page',
  CREATE_INCIDENT_TYPE_PAGE = 'create_incident_type_page',
  UPDATE_INCIDENT_TYPE_PAGE = 'update_incident_type_page',
  DELETE_INCIDENT_TYPE_PAGE = 'delete_incident_type_page',
  LOCATIONS_PAGE = 'locations_page',
  CREATE_LOCATION_PAGE = 'create_location_page',
  UPDATE_LOCATION_PAGE = 'update_location_page',
  DELETE_LOCATION_PAGE = 'delete_location_page',
  ITEMS_PAGE = 'items_page',
  CREATE_ITEM_PAGE = 'create_item_page',
  UPDATE_ITEM_PAGE = 'update_item_page',
  DELETE_ITEM_PAGE = 'delete_item_page',
  USERS_PAGE = 'users_page',
  CREATE_USER_PAGE = 'create_user_page',
  UPDATE_USER_PAGE = 'update_user_page',
  DELETE_USER_PAGE = 'delete_user_page',
}