-- AlterTable
ALTER TABLE "permission" ALTER COLUMN "name" SET DATA TYPE VARCHAR(100),
ALTER COLUMN "key" SET DATA TYPE VARCHAR(100);

-- AlterTable
ALTER TABLE "role" ALTER COLUMN "name" SET DATA TYPE VARCHAR(100),
ALTER COLUMN "key" SET DATA TYPE VARCHAR(100);
